site_name: Tomb of Annihilation Notes
site_description: Tomb of Annihilation Notes
site_url: https://tiamcdowell.github.io/TombOfAnnihilationNotes/

theme:
    name: 'material'
    font:
        text: Karla
        code: Ubuntu Mono
    language: en
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
plugins:
  - search
  - ezlinks:
        wikilinks: true
  # - mermaid2
  # - awesome-pages
  - tooltipster-links
  - embed_file
extra_javascript:
  - assets/js/mathjax.js
  - assets/js/utils.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/tooltipster.bundle.js  
extra_css:
    - assets/css/img-grids-floats.css
    - assets/css/utils.css
    - assets/css/custom_attributes.css
    - assets/css/tooltipster.bundle.min.css
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
extra:
  generator: false
